import image from '../../images/svg_1.svg'
import imageTwo from '../../images/svg_2.svg'
import imageThree from '../../images/svg_3.svg'

export const dataObjone = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'test',
    headline: 'Test2',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at urna leo. In dapibus, lorem quis commodo fermentum, magna dui interdum velit, fringilla rutrum erat nibh sit amet urna.',
    buttonLabel: 'Test4',
    imgStart: false,
    image: image,
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false,
}
export const dataObjTwo = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'test',
    headline: 'Test2',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at urna leo. In dapibus, lorem quis commodo fermentum, magna dui interdum velit, fringilla rutrum erat nibh sit amet urna.',
    buttonLabel: 'Test4',
    imgStart: true,
    image: imageTwo,
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: true,
}
export const dataObjThree = {
    id: 'news',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'test',
    headline: 'Test2',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at urna leo. In dapibus, lorem quis commodo fermentum, magna dui interdum velit, fringilla rutrum erat nibh sit amet urna.',
    buttonLabel: 'Test4',
    imgStart: false,
    image: imageThree,
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false,
}
export const dataObjFour = {
    id: 'exercises',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'test',
    headline: 'Test2',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at urna leo. In dapibus, lorem quis commodo fermentum, magna dui interdum velit, fringilla rutrum erat nibh sit amet urna.',
    buttonLabel: 'Test4',
    imgStart: true,
    image: imageThree,
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: true,
}